"$schema" = 'https://starship.rs/config-schema.json'      # Get editor completions based on the config schema

# TODO
  # https://starship.rs/config/#jobs
  #kubernetes
  #helm
  #go
  #docker
  #nix-shell
  #open-stack
  #vagrant

add_newline       = true                  # Inserts a blank line between shell prompts
scan_timeout      = 100
command_timeout   = 1000

format = '''
[â•­](bold green)$directory$sudo$git_branch$git_commit$git_state$git_metrics$package$shlvl$jobs$fill$status$cmd_duration
[â•°](bold green)$username@$hostname   '''

[fill]
symbol = ' '

[username]
format              = '[$user]($style)'
show_always         = true
disabled            = false
#style_user         = 'white bold'
#style_root         = 'black bold'

[hostname]
format              = '[$hostname](bold blue)[$ssh_symbol](bold magenta)'
ssh_symbol          = '(ssh)'
ssh_only            = false
disabled            = false

[directory]
format              = '[$path]($style)[$read_only]($read_only_style) '
read_only 	        = 'ğŸ”’'
read_only_style     = 'red'
truncation_length   = 2
truncate_to_repo    = true

[cmd_duration]
format              = '[$duration]($style)'
style               = 'bold yellow'
min_time            = 2_000
show_milliseconds   = true

[git_branch]
format              = '[$branch(:$remote_branch)]($style) '
symbol              = "branch "
style 	            = 'bold purple'

#[homelab_prompt]
#command             = "homelab_prompt"
#format 	            = "[($output )]($style)"
#style 	            = "bold purple"

[git_commit]
format              = '[\($hash$tag\)]($style) '
commit_hash_length  = 7
tag_symbol          = ''

[git_state]
#format             = '[\($state( $progress_current of $progress_total)\)]($style) '
format              = '\([$state( $progress_current/$progress_total)]($style)\) '
cherry_pick         = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style         = 'bold blue'
format              = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format              = '([\[$all_status$ahead_behind\]]($style) ) '
ignore_submodules   = false

[container]         # displays a symbol and container name inside a container
format              = '[$symbol \[$name\]]($style) '
symbol              = 'â¬¢'
style               = 'bold red dimmed'

[sudo]
format              = '[$symbol]($style) '
symbol              = "sudo"
style               = 'bold green'
disabled            = false

[package]           # shown when the current dir is a pkg repo
format              = '[$symbol$version]($style) '
symbol              = 'ğŸ“¦'
version_format      = 'v${raw}'
display_private     = true

#[character]
#success_symbol = "[->](bold green)"
#error_symbol = "[x](bold red)"
#vimcmd_symbol = "[vim](bold green)"

[status]
format              = '[$symbol$common_meaning$signal_name $status$maybe_int]($style) '
style               = ''          # 'bg:blue'
symbol              = ''          # 'âŒ'
success_symbol      = ''          # 'ğŸŸ¢'
not_executable_symbol = ''        # 'ğŸš«'
not_found_symbol    = ''          # 'ğŸ”'
sigint_symbol 	    = ''          # 'ğŸ§±'
signal_symbol 	    = ''          # 'âš¡'
map_symbol          = true
disabled            = false

[shlvl]
format      = "[$shlvl]($style)"
style 	    = "bold yellow"
threshold   = 3
disabled    = false

[jobs]
format              = '[$symbol$number]($style) '
style 	            = 'bold blue'
symbol              = '+'
number_threshold    = 1
symbol_threshold    = 1

[c]
symbol = "C "

[cmake]
symbol = "cmake "

[docker_context]
symbol = "docker "

[python]
symbol = "py "

[terraform]
symbol = "terraform "
